# Sample .travis.yml for R projects from https://github.com/craigcitro/r-travis

language: c

before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap

install:
  - ./travis-tool.sh install_deps
  - sudo apt-get install texlive-latex-extra

script: ./travis-tool.sh run_tests

after_failure:
  - ./travis-tool.sh dump_logs

env:
  - WARNINGS_ARE_ERRORS=1
  - global:
    - R_CHECK_ARGS="--no-manual --timings"
    - R_BUILD_ARGS="--no-manual"

notifications:
  email:
    on_success: change
    on_failure: change
